function [fitresult, gof] = rPowerFit(gens, r0)
%CREATEFIT(GENS,R0DIAG)
%  Create a fit.
%
%  Data for 'V(1,1)' fit:
%      X Input : gens
%      Y Output: r0diag
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Jan-2019 12:56:20


%% Fit: 'V(1,1)'.
[xData, yData] = prepareCurveData( gens, r0 );

% Set up fittype and options.
ft = fittype( 'k^x+b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.118997681558377 0.830828627896291];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure;

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend('off' );
% Label axes
xlabel Generation
ylabel R_0
grid on
text(2,1,sprintf('R_0(x)=%.3f^x+%.3f\nR^2=%.3f', fitresult.k, fitresult.b,gof.rsquare))

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend('off' );
% Label axes
xlabel Generation
ylabel Residuals
grid on


